name: CI

on:
  push:
    branches:
      - master
    tags:
      - '**'
  pull_request:

env:
  NUMBA_NUM_THREADS: 1
  MPLBACKEND: Agg
  PYTEST_ADDOPTS: --color=yes

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Runs pre-commit hooks
        uses: pre-commit/action@v3.0.0
        with:
          extra_args: --files $(git diff origin/main --name-only)

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        ctapipe-version: [v0.19.1]
        install-method: [ "mamba", "pip" ]

    defaults:
      run:
        # We need login shells (-l) for micromamba to work.
        shell: bash -leo pipefail {0}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Python version
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml

      - name: Mamba setup
        if: matrix.install-method == 'mamba'
        uses: mamba-org/provision-with-micromamba@v15
        with:
          environment-name: "ci"
          environment-file: environment.yml

      - name: Python setup
        if: matrix.install-method == 'pip'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install dependencies
        env:
          CTAPIPE_VERSION: ${{ matrix.ctapipe-version }}

        run: |
          python --version
          echo "Installing additional pip packages"
          # we install ctapipe using pip to be able to select any commit, e.g. the current master
          pip install \
             "git+https://github.com/cta-observatory/ctapipe@$CTAPIPE_VERSION" \
              pytest-cov

          echo "pip install -e ."
          pip install -e .

      - name: Tests
        run: |
          pytest --cov=nectarchain --cov-report=xml

      - uses: codecov/codecov-action@v3
